CREATE TABLE if not exists USER_INFO(ID UUID PRIMARY KEY, NAME VARCHAR(255), MAIL VARCHAR(255), INFO VARCHAR(255));

CREATE UNIQUE INDEX UI_NAME ON USER_INFO(NAME);
CREATE UNIQUE INDEX UI_MAIL ON USER_INFO(MAIL);

CREATE TABLE if not exists USER_PASS(ID UUID PRIMARY KEY,ID_USER UUID references USER_INFO(ID),PASS VARCHAR(255));

CREATE TABLE if not exists USER_TOKEN(ID UUID PRIMARY KEY, ID_USER UUID references USER_INFO(ID), TOKEN VARCHAR(255));

CREATE UNIQUE INDEX UT_ID_USER ON USER_TOKEN(ID_USER);
CREATE UNIQUE INDEX UT_TOKEN ON USER_TOKEN(TOKEN);