CREATE TABLE if not exists USER_INFO(ID UUID PRIMARY KEY, NAME VARCHAR(255), MAIL VARCHAR(255), INFO VARCHAR(255))
CREATE TABLE if not exists USER_PASS(ID UUID PRIMARY KEY,ID_USER UUID ,PASS VARCHAR(255))
CREATE TABLE if not exists USER_TOKEN(ID UUID PRIMARY KEY, ID_USER UUID, TOKEN VARCHAR(255))